generic-service:
  nameOverride: hmpps-arns-frontend-components
  productId: 'HMPPS509' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  # serviceAccountName: "hmpps-arns-frontend-components"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-arns-frontend-components
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-arns-frontend-components-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    # These secrets are created by terraform.
    hmpps-arns-frontend-components-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    # This secret will need to be created in your namespace (note it isn't in hmpps-templates-dev)
    # IRSA configuration in your namespace will also be required, and then uncomment serviceAccountName above.
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-arns-frontend-components
