---
# Per environment values which override defaults in hmpps-arns-frontend-components/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: arns-frontend-components-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://arns-frontend-components-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    ARNS_API_URL: "http://hmpps-arns-frontend-components-wiremock/arns-api"

generic-prometheus-alerts:
  alertSeverity: hmpps-arns-risk-actuarial-nonprod
