---
# Per environment values which override defaults in hmpps-arns-frontend-components/values.yaml

generic-service:
  ingress:
    host: arns-frontend-components.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://arns-frontend-components-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-arns-risk-actuarial-prod
